### ISSUE TITLE
Having a badge requirement of 0 on Mt silver badge requirement fails to generate

### ISSUE THREAD

**Issue by f-raZ0R** [erudnick-cohen/Pokemon-Crystal-Item-Randomizer#20]
Step 1: create a seed with a 0 badge required mt silver
Step 2:wait
Step 3:get this error
Traceback (most recent call last): File "RunGUI.py", line 108, in runRandomizer File "RunCustomRandomizationAssumedFill.py", line 219, in randomizeRom File "RandomizerRom.py", line 43, in WriteOakBadgeCheckNumber ValueError: mmap item value must be in range(0, 256)

**Comment by erudnick-cohen** [comment]
randomizer should now have message to prevent this
